INSERT INTO products (name, userID, description, imageUrl) VALUES ("Gibson ES-225", 1, "Featuring a laminated maple/mahogany neck, this electric guitar is easily the most indentifiable in the Gibson lineup. Produced by Gibson Guitar Corp. between 1955 and 1959, this instrument can be noted as the first thinline hollowbody guitar produced by Gibson. To get your hands on a custom ES-225 today, you'll be looking at spending upwards of $2,000.", "https://cdn.shopify.com/s/files/1/0975/2962/products/ES_225_Full_2048x.jpg?v=1529467785");
INSERT INTO products (name, userID, description, imageUrl) VALUES ("Gibson Les Paul Classic Electric Guitar", 1, "Available on the market today for $1,659, this 60's style guitar comes equipped with a mahogany back nd a maple top, as well as a slim taper mahogany neck paired with a rosewood fingerboard. Gloss finsihed.", "https://images.reverb.com/image/upload/s--i_0KDD9A--/f_auto,t_large/v1556567601/oji4blte8mq65czvhwic.jpg");
INSERT INTO products (name, userID, description, imageUrl) VALUES ("Yamaha C6", 2, "Labeled at a pricey sum of $19,800, this 2010 model piano features  responsive key action as big projecting sound. To get your hands on a brand new C6, you would have to spend around close to $80,000. This piano comes equipped with an advanced scale design, solid copper wound bass strings, specifally designed hammer shanks, along with many other impressive features.", "https://worldsfinestpianos.com/wp-content/uploads/2020/03/Yamaha-C6-ID-6280946.jpg");
INSERT INTO products (name, userID, description, imageUrl) VALUES ("Steinway Model Z", 3, "Orignally owened by John Lennon, this beautiful grand piano can be fetched for $2,370,000. This is THE piano that the class 'Imagine' was written on. Although Steinway and Sons is known for it's exquisite quality of instruments, without having a previous owner of John Lennon this piano would be nowhere near what it is worth today.", "https://img.klaviano.com/files/05-2017/ad404017/large_1494416403375248664.jpg");
INSERT INTO products (name, userID, description, imageUrl) VALUES ("Yamaha SV-200", 4, "This uniquely designed instrument is both electric and acoustic. Available today for only $1,260; this piece comes with broad felxibility to adjust for multiple playing styles, as well as amplification equipment. The Yamaha SV-200 is made using spruce, maple, and ebony woods.", "https://www.yamaha.com/yamahavgn/PIM/Images/534E8B962FF64573B98DE5594A186562_12073_735x735_522cf218197aced0f536dfa2f870b04c.jpg");
INSERT INTO products (name, userID, description, imageUrl) VALUES ("6-String Fretted Cobra Cello", 5, "Get a hold of one today for $5,899 and get an over the shoulder harness system along with your order. Fitted with both a low F string and a high E string, this cello allows the musician extend your range positively and negatively. Taking advantage of a light weight, hollow body construction, this cello is quite eaasy to manouver.", "https://www.electricviolinshop.com/media/catalog/product/cache/afad95d7734d2fa6d0a8ba78597182b7/c/o/cobra6fglossblack_right3-4s.jpg");
INSERT INTO products (name, userID, description, imageUrl) VALUES ("Yamaha 677H", 6, "This professional flute is made for an advancing student or a very skilled hobbyist. It combines the brilliance of nickel silver keys along with a sterling silver headjoint and body. Available for $4,089 on wwbw.com.", "https://images.reverb.com/image/upload/s--NTlJDPDI--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1519984091/v37tg2qlsjwefnszmgdl.jpg");


