

INSERT INTO products (name, username, description) VALUES ("Gibson-Es325-guitars", "Charlie", "An electric guitar that stands for Electric Spanish that is also a semi acoustic guitar. Gibson created this type of guitar to find middle ground to have a warmer tone and flexible for a wide range of music such as blues, jazz, and rock. Most notable legends that use this guitar stem from Chuck Berry, Eric Clapton, Matry Mcfly(Yes, that marty!), and of course my favorite artist Tom Delonge of Angels and Airwaves.")
INSERT INTO products (name, username, description) VALUES ("Gibson-Les-Paul-guitars", "Charlie", "Named after and endorsed by famed jazz musician made in 1952 is a very common guitar for many legends of rock and roll and other genres like Chad Gilbert of New Found Glory.")
INSERT INTO products (name, username, description) VALUES ("Fender-stratocaster-guitars", "Nora", "Probably one of the most famous guitars used by none other then Jimi Hendrix.")
INSERT INTO products (name, username, description) VALUES ("Fender-jaguar-guitars", "Nora", "A sort of upgraded model of its predecessor the jazz master was popular among punk rock.")
INSERT INTO products (name, username, description) VALUES ("Ephiphone-SG-guitars", "Chand", "A copycat and somewhat cheaper model of it's owner Angus Young of AC/DC goes lighter on your wallet.")
INSERT INTO products (name, username, description) VALUES ("Fender-jazz-bass", "Jean", "Fender strikes again with their bass models with Mark Hoppus as one of its many users.")
INSERT INTO products (name, username, description) VALUES ("Rickenbacker-bass", "Jean", "Used by the great Paul McCartney, enough said.")
INSERT INTO products (name, username, description) VALUES ("Orange-County-drums", "Travis", "A home based company in Anahiem California home of the mighty ducks, but custom made kits are only for Travis Barker and Atom Willard. No one else can get anymore because Joey Jordison had them make him a 20 peice set or some huge number.")
INSERT INTO products (name, username, description) VALUES ("DW-drums", "Travis", "While using the brand from Orange County Atom Willard is an official endorser of Drum workshop.")
INSERT INTO products (name, username, description) VALUES ("Yamaha-synthesizer", "Brendon", "I don't what Yamaha doesn't make but I know they make great electric keyboards adding a synthesizer to it makes it even better.")